---
spring:
  profiles: eureka1
server:
  port: 8761                    
eureka:
  instance:
    hostname: eureka1
    # hostname: 0.0.0.0
    # hostname: eureka1         
  client:
    # registerWithEureka: false
    # fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: eureka2
server:
  port: 8762                    
eureka:
  instance:
    hostname: eureka2
    # hostname: 0.0.0.0
    # hostname: eureka2         
  client:
    # registerWithEureka: false
    # fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

